In [1]:
import numpy as np

**a[start:stop:step]**

**Example**

In [5]:
a = np.array([3,4,2,5,6,2,8])

print(a)

[3 4 2 5 6 2 8]


In [6]:
s = a[:5]

print(s)

[3 4 2 5 6]


In [7]:
s = a[2:]

print(s)

[2 5 6 2 8]


In [8]:
s = a[5:]

print(s)

[2 8]


In [9]:
s =a[2:6]

print(s)

[2 5 6 2]


In [10]:
s =a[2:6:2]

print(s)

[2 6]
